spring:
  application:
    name: loadbalance
  cloud:
    config:
      uri: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
    users:
      path: /api/**
      service-id: service-atmdeposit
      
# Discovery Server Access
eureka:
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8180/eureka/

server:
  port: 8082   # HTTP (Tomcat) port